/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppLogbookRouteImport } from './routes/app.logbook'
import { Route as AppListingAiRouteImport } from './routes/app.listing-ai'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppInventoryIndexRouteImport } from './routes/app.inventory.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppTeamRolesRouteImport } from './routes/app.team.roles'
import { Route as AppInventoryChairIdRouteImport } from './routes/app.inventory.$chairId'
import { Route as AppChairNewRouteImport } from './routes/app.chair.new'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AppChairChairIdEditRouteImport } from './routes/app.chair.$chairId.edit'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLogbookRoute = AppLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AppRoute,
} as any)
const AppListingAiRoute = AppListingAiRouteImport.update({
  id: '/listing-ai',
  path: '/listing-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRolesRoute = AppTeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppInventoryChairIdRoute = AppInventoryChairIdRouteImport.update({
  id: '/inventory/$chairId',
  path: '/inventory/$chairId',
  getParentRoute: () => AppRoute,
} as any)
const AppChairNewRoute = AppChairNewRouteImport.update({
  id: '/chair/new',
  path: '/chair/new',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppChairChairIdEditRoute = AppChairChairIdEditRouteImport.update({
  id: '/chair/$chairId/edit',
  path: '/chair/$chairId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/listing-ai': typeof AppListingAiRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/': typeof AppIndexRoute
  '/app/chair/new': typeof AppChairNewRoute
  '/app/inventory/$chairId': typeof AppInventoryChairIdRoute
  '/app/team/roles': typeof AppTeamRolesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/chair/$chairId/edit': typeof AppChairChairIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/listing-ai': typeof AppListingAiRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app': typeof AppIndexRoute
  '/app/chair/new': typeof AppChairNewRoute
  '/app/inventory/$chairId': typeof AppInventoryChairIdRoute
  '/app/team/roles': typeof AppTeamRolesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/inventory': typeof AppInventoryIndexRoute
  '/app/chair/$chairId/edit': typeof AppChairChairIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/listing-ai': typeof AppListingAiRoute
  '/app/logbook': typeof AppLogbookRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/': typeof AppIndexRoute
  '/app/chair/new': typeof AppChairNewRoute
  '/app/inventory/$chairId': typeof AppInventoryChairIdRoute
  '/app/team/roles': typeof AppTeamRolesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/inventory/': typeof AppInventoryIndexRoute
  '/app/chair/$chairId/edit': typeof AppChairChairIdEditRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/unsubscribe'
    | '/app/expenses'
    | '/app/listing-ai'
    | '/app/logbook'
    | '/app/settings'
    | '/app/team'
    | '/email/unsubscribe'
    | '/app/'
    | '/app/chair/new'
    | '/app/inventory/$chairId'
    | '/app/team/roles'
    | '/lovable/email/suppression'
    | '/app/inventory/'
    | '/app/chair/$chairId/edit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/unsubscribe'
    | '/app/expenses'
    | '/app/listing-ai'
    | '/app/logbook'
    | '/app/settings'
    | '/app/team'
    | '/email/unsubscribe'
    | '/app'
    | '/app/chair/new'
    | '/app/inventory/$chairId'
    | '/app/team/roles'
    | '/lovable/email/suppression'
    | '/app/inventory'
    | '/app/chair/$chairId/edit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/unsubscribe'
    | '/app/expenses'
    | '/app/listing-ai'
    | '/app/logbook'
    | '/app/settings'
    | '/app/team'
    | '/email/unsubscribe'
    | '/app/'
    | '/app/chair/new'
    | '/app/inventory/$chairId'
    | '/app/team/roles'
    | '/lovable/email/suppression'
    | '/app/inventory/'
    | '/app/chair/$chairId/edit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logbook': {
      id: '/app/logbook'
      path: '/logbook'
      fullPath: '/app/logbook'
      preLoaderRoute: typeof AppLogbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/listing-ai': {
      id: '/app/listing-ai'
      path: '/listing-ai'
      fullPath: '/app/listing-ai'
      preLoaderRoute: typeof AppListingAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/': {
      id: '/app/inventory/'
      path: '/inventory'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/team/roles': {
      id: '/app/team/roles'
      path: '/roles'
      fullPath: '/app/team/roles'
      preLoaderRoute: typeof AppTeamRolesRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/app/inventory/$chairId': {
      id: '/app/inventory/$chairId'
      path: '/inventory/$chairId'
      fullPath: '/app/inventory/$chairId'
      preLoaderRoute: typeof AppInventoryChairIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chair/new': {
      id: '/app/chair/new'
      path: '/chair/new'
      fullPath: '/app/chair/new'
      preLoaderRoute: typeof AppChairNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chair/$chairId/edit': {
      id: '/app/chair/$chairId/edit'
      path: '/chair/$chairId/edit'
      fullPath: '/app/chair/$chairId/edit'
      preLoaderRoute: typeof AppChairChairIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTeamRouteChildren {
  AppTeamRolesRoute: typeof AppTeamRolesRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamRolesRoute: AppTeamRolesRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppExpensesRoute: typeof AppExpensesRoute
  AppListingAiRoute: typeof AppListingAiRoute
  AppLogbookRoute: typeof AppLogbookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChairNewRoute: typeof AppChairNewRoute
  AppInventoryChairIdRoute: typeof AppInventoryChairIdRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppChairChairIdEditRoute: typeof AppChairChairIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExpensesRoute: AppExpensesRoute,
  AppListingAiRoute: AppListingAiRoute,
  AppLogbookRoute: AppLogbookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChairNewRoute: AppChairNewRoute,
  AppInventoryChairIdRoute: AppInventoryChairIdRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppChairChairIdEditRoute: AppChairChairIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
